### ISSUE TITLE
Duplicated definition of class TensorboardExperiment:

### ISSUE THREAD

**Issue by JimOgren** [ArjanCodes/2021-data-science-refactor#1]
Hi Arjan! 
In the YouTube tutorial you erased `class TensorboardExperiment` from the file tracking.py since it was moved to tensorboard.py. In the /after/ directory, however, it seems the class definition seem to appear twice. 

Keep up the nice work! I really like your videos :)

Cheers!
Jim

**Comment by egges** [comment]
Thanks for pointing this out - good catch! I've removed the double class definition. Happy you enjoy the videos!
